#!/bin/sh
######################################################################
#
# Description : Udisks-Glue
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions


NAME="udisks-glue"
# PID (created by start-stop-daemon -m)
PID="udisks-glue"
PID_FILE=/var/run/$PID.pid
DAEMON="udisks-glue"
DAEMON_OPTS="--config /etc/udisks-glue.conf --pidfile $PID_FILE"
DAEMON_PATH="/usr/bin"
DAEMON_FILE=$DAEMON_PATH/$DAEMON


case "$1" in
    start)
        log_boot_start
		boot_mesg -n "Starting $NAME..."
        start-stop-daemon -q -b -x $DAEMON_FILE -S -- $DAEMON_OPTS
        if [ $? -eq 0 ]; then
            boot_mesg "[ OK ]"
		else
            boot_mesg "[FAIL]"
        fi
		log_boot_finish
        ;;
    stop)
        boot_mesg -n "Stopping $NAME..."
        start-stop-daemon -q -p $PID_FILE -K
        if [ $? -eq 0 ]; then
            boot_mesg "[ OK ]"
		else
            boot_mesg "[FAIL]"
        fi
		# --remove-pidfile not supported by busybox
		#[ $RETVAL = 0 ] && rm -f $PID_FILE
        if [ -f $PID_FILE ]; then
            rm -f $PID_FILE
        fi
        ;;
    restart | force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
        exit 3
        ;;
    status)
        status_of_proc $DAEMON "udisks-glue"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
