#!/bin/sh
######################################################################
#
# Description : Udisks-Glue
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions


NAME="udisks-glue"
# PID (created by start-stop-daemon -m)
PID="udisks-glue"
PID_FILE=/var/run/$PID.pid
DAEMON="udisks-glue"
DAEMON_OPTS="-c /etc/udisks-glue.conf"
DAEMON_PATH="/usr/bin/"
DAEMON_FILE=$DAEMON_PATH/$DAEMON


case "$1" in
    start)
        log_boot_start
		boot_mesg -n "Starting $NAME..."
        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
		log_boot_finish
        ;;
    stop)
        boot_mesg -n "Starting $NAME..."
        start-stop-daemon -q -p $PIDFILE -K
        rm -f $PIDFILE
        ;;
    restart | force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
        exit 3
        ;;
    status)
        status_of_proc $DAEMON "udisks-glue"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
