#!/bin/sh

# APPLICATION
NAME="ZMQ forwarder"
DAEMON="/mnt/PIHU_APP/defender-headunit/d_zmq_forwarder.py"
DAEMONOPTS=""

[ -x $DAEMON ] || exit 1

retval=0

# PID (created by start-stop-daemon -m)
PIDFILE=/var/run/zmqfwd.pid

start() {
        if [ -f $DAEMON ]; then
          echo "Starting $NAME..."
          start-stop-daemon -b -x $DAEMON -m -p $PIDFILE -S -- $DAEMONOPTS
          retval=$?
		else
          echo "$DAEMON not found!"
        fi
}

stop() {
        echo "Stopping $NAME"
        start-stop-daemon -p $PIDFILE -K
        retval=$?
		# --remove-pidfile not supported by busybox
        if [ -f $PIDFILE ]; then
            rm -f $PIDFILE
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $retval
