#!/bin/sh

# APPLICATION
NAME="ZMQ forwarder"
DAEMON="zmq_forwarder.py"
DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
DAEMON_OPTS=""

if [ -x $DAEMON_PATH/$DAEMON ]; then
  echo "Can't execute $DAEMON_PATH/$DAEMON"
  exit 1
fi

retval=0

# PID (created by start-stop-daemon -m)
PIDFILE=/var/run/$DAEMON.pid

start() {
        if [ -f $DAEMON_PATH/$DAEMON ]; then
          echo "Starting $NAME..."
          start-stop-daemon -b -x $DAEMON_PATH/$DAEMON -m -p $PIDFILE -S -- $DAEMON_OPTS
          retval=$?
		else
          echo "$DAEMON not found!"
        fi
}

stop() {
        echo "Stopping $NAME"
        start-stop-daemon -p $PIDFILE -K
        retval=$?
		# --remove-pidfile not supported by busybox
        if [ -f $PIDFILE ]; then
            rm -f $PIDFILE
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $retval
