#!/bin/sh
######################################################################
#
# Description : GPIO init / beeper
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions

# Enabling GPIO output on pin 6 (beeper)
PIN="6"

start() {
    log_boot_start
    gpio write 6 0
    gpio mode 6 out
    gpio write 6 1
    gpio write 6 0
	log_boot_finish
}

case "$1" in
  start)
        start
        ;;
  *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?