#!/bin/sh
######################################################################
#
# Description : Jack
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions

# APPLICATION
NAME="JACK"
# PID (created by start-stop-daemon -m)
PID="jack"
PID_FILE=/var/run/$PID.pid
DAEMON="jackd"
DAEMON_OPTS="--realtime -d dummy"
#if line-in is required: (this won't lock the output (?))
#DAEMON_OPTS="--realtime -d alsa -C hw0,1"
DAEMON_PATH="/usr/bin"
DAEMON_FILE=$DAEMON_PATH/$DAEMON

ECA_NAME="ECASOUND"
ECA_PID = "ecasound"
ECA_DAEMON="ecasound"
ECA_DAEMON_OPTS="--server -z:nodb -z:mixmode,sum -s:/etc/ecasound/active.ecs"
ECA_DAEMON_PATH="/usr/bin"
ECA_DAEMON_FILE=$ECA_DAEMON_PATH/$ECA_DAEMON
ECA_PID_FILE=/var/run/$ECA_PID.pid

ECA_DAEMON_FILE="DONT-RUN-DAEMON-USE-CONTROL-ECA-PY"

RETVAL=0

start() {
    log_boot_start
    if [ -f $DAEMON_FILE ]; then
        boot_mesg -n "Starting $NAME..."
        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
        RETVAL=$?
    else
	    #RETVAL=-1
		RETVAL=1
        echo "$DAEMON not found!"
    fi
	
    if [ -f $ECA_DAEMON_FILE ]; then
        boot_mesg -n "Starting $ECA_NAME..."
		start-stop-daemon -b -x $ECA_DAEMON_FILE -m -p $ECA_PID_FILE -S -- $ECA_DAEMON_OPTS
        RETVAL=$?
    else
	    #RETVAL=-1
		RETVAL=1
        echo "$ECA_DAEMON_FILE not found!"
    fi
	log_boot_finish
}

stop() {
        boot_mesg -n "Stopping $NAME..."
        start-stop-daemon -q -p $PID_FILE -K
        RETVAL=$?
		# --remove-pidfile not supported by busybox
		#[ $RETVAL = 0 ] && rm -f $PID_FILE
        if [ -f $PID_FILE ]; then
            rm -f $PID_FILE
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

# Print OK/FAIL
if [ $RETVAL -eq 0 ]; then
    echo "[ OK ]"
else
    echo "[FAIL]"
fi

exit $RETVAL
