#!/bin/sh

echo $(date "+%H:%M.%s") $0 $1 >> /root/boot.log

# APPLICATION
NAME="JACK"
# PID (created by start-stop-daemon -m)
PID="jack"
PID_FILE=/var/run/$PID.pid
DAEMON="jackd"
DAEMON_OPTS="--realtime -d dummy"
DAEMON_PATH="/usr/bin"
DAEMON_FILE=$DAEMON_PATH/$DAEMON

RETVAL=0

start() {
    if [ -f $DAEMON_FILE ]; then
        echo "Starting $NAME..."
        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
        RETVAL=$?
    else
	    RETVAL=-1
        echo "$DAEMON not found!"
    fi
}

stop() {
        echo "Stopping $NAME"
        start-stop-daemon -p $PID_FILE -K
        RETVAL=$?
		# --remove-pidfile not supported by busybox
		#[ $RETVAL = 0 ] && rm -f $PID_FILE
        if [ -f $PID_FILE ]; then
            rm -f $PID_FILE
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

# Print OK/FAIL
if [ $RETVAL -eq 0 ]; then
    echo "[ OK ]"
else
    echo "[FAIL]"
fi

exit $RETVAL
