#!/bin/sh
######################################################################
#
# Description : ZeroMQ
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions

# APPLICATION
NAME="ZMQ forwarder"
# PID (created by start-stop-daemon -m)
PID="zmq_forwarder"
PID_FILE=/var/run/$PID.pid
DAEMON="zmq_forwarder.py"
DAEMON_OPTS="-b"
DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
DAEMON_FILE=$DAEMON_PATH/$DAEMON

RETVAL=0

start() {
    log_boot_start
    if [ -f $DAEMON_FILE ]; then
        echo "Starting $NAME..."
        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
        RETVAL=$?
    else
	    RETVAL=-1
        echo "$DAEMON not found!"
    fi
    log_boot_finish
}

stop() {
        echo "Stopping $NAME"
        start-stop-daemon -p $PID_FILE -K
        RETVAL=$?
		# --remove-pidfile not supported by busybox
		#[ $RETVAL = 0 ] && rm -f $PID_FILE
        if [ -f $PID_FILE ]; then
            rm -f $PID_FILE
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

# Print OK/FAIL
if [ $RETVAL -eq 0 ]; then
    echo "[ OK ]"
else
    echo "[FAIL]"
fi

exit $RETVAL
