#!/bin/sh
######################################################################
#
# Description : Ecasound
# Authors     : Sjoerd Venema
# Version     : 00.01
# Notes       : 
#
########################################################################

. /etc/sysconfig/functions

#
# Starts scripts in qp_-folder
#

#[ -f /root/WLAN-AP ] || exit 0
export HU_SOURCE=smb

EXEC_PATH=/etc/init.d/qp_smb
EXEC_PATH=/etc/init.d/quickplay

retval=0

case "$1" in
    start)
        log_boot_start
        printf "Start QuickPlay"
        for i in $EXEC_PATH/S??* ;do
            # Ignore dangling symlinks (if any).
            [ ! -f "$i" ] && continue
                case "$i" in
                    *.sh)
                        # Source shell script for speed.
                        (
                            trap - INT QUIT TSTP
                            set start
                            . $i
                        )
                        ;;
                    *)
                        # No sh extension, so fork subprocess.
                        if [[ "$i" == "S70headunit" -a ! "$retval_sum" == "0" ]]; then
                            echo "Skipping early Headunit start"
                        else
                            $i start
                            retval_sum=`expr $retval_sum+$?`
                        fi
                    ;;
            esac
        done
        log_boot_finish
        ;;
    stop)
	    printf "Cuz the other failz"
    stopX)
                printf "Stopping execution of wlan-ap scripts"
                for i in $(ls -r $EXEC_PATH/S??*) ;do

                     # Ignore dangling symlinks (if any).
                     [ ! -f "$i" ] && continue

                     case "$i" in
                        *.sh)
                            # Source shell script for speed.
                            (
                                trap - INT QUIT TSTP
                                set stop
                                . $i
                            )
                            ;;
                        *)
                            # No sh extension, so fork subprocess.
                            $i stop
                            ;;
                    esac
                done

                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit 0
