#!/bin/sh
#Main headunit script

# APPLICATION
NAME="Headunit"
DAEMON="/mnt/PIHU_APP/defender-headunit/hu.py"
DAEMONOPTS=""

# PID (created by application)
PIDFILE=/var/run/hu.pid

start() {
        if [ -f $DAEMON ]; then
          echo "Starting $NAME..."
          $DAEMON $DAEMONOPTS &
        else
          echo "$DAEMON not found!"
        fi
}

stop() {
        if [ -f $PIDFILE ]; then
            echo "Stopping $NAME"
            PID=`cat $PIDFILE`
            kill -HUP $PID
            rm -f $PIDFILE
        else
            echo "$PIDFILE not found, aborting..."
        fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?