#!/bin/sh

DAEMON="/mnt/PIHU_APP/defender-headunit/d_dbus_vol.py"

start() {
        if [ -f $DAEMON ]; then
          echo "Script: ${DAEMON} found.."
          $DAEMON &
        else
          echo "${DAEMON} not found!"
        fi
}

stop() {
        echo "Not yet implemented"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?